module.exports = {
  upgrade: true,
  reject: [
    'electron',
    'chalk',
    'del',
    'comlink',
    '@types/comlink',
    'react',
    'react-dom',
    'image-size',
    'message2call',
    '@types/ws',
    'eslint',
    '@types/node',
    'electron-debug',
    'eslint-webpack-plugin',
    'typescript',
    'undici',
  ],
};
